AWSTemplateFormatVersion : "2010-09-09"

#   --------------------------------------------------------
#   Version History
#
#   v1.0  L. Leonard   Initial Version
#   --------------------------------------------------------

Description: >-
  v1.0. creation of the roles 

Parameters:
  SessionDurationInSec:
    Type: Number
    Default: 3600
    # 5 minutes
    MinValue: 300
    # 12 hours
    MaxValue: 43200
    Description: Session maximum duration in seconds

Resources:
  rDeployerRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AWSCloudTrailReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
      MaxSessionDuration: !Ref SessionDurationInSec
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: DeployerRole
      Path: "/"
      Policies:
        - PolicyName: DeployerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - "kms:Create*"
                - "kms:Describe*"
                - "kms:Enable*"
                - "kms:List*"
                - "kms:Put*"
                - "kms:Update*"
                - "kms:Revoke*"
                - "kms:Disable*"
                - "kms:Get*"
                - "kms:Delete*"
                - "kms:ScheduleKeyDeletion"
                - "kms:CancelKeyDeletion"
                - "kms:TagResource"
                - "kms:UntagResource"
              Resource: "*"
      Tags:
        - Key: Created-in-stack
          Value: !Sub '${AWS::StackId}'
  rKeyManagerRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: !Ref SessionDurationInSec
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: KeyManagerRole
      Path: "/"
      Policies:
        - PolicyName: KeyManagerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - "kms:Create*"
                - "kms:Describe*"
                - "kms:Enable*"
                - "kms:List*"
                - "kms:Put*"
                - "kms:Update*"
                - "kms:Revoke*"
                - "kms:Disable*"
                - "kms:Get*"
                - "kms:Delete*"
                - "kms:ScheduleKeyDeletion"
                - "kms:CancelKeyDeletion"
                - "kms:TagResource"
                - "kms:UntagResource"
              Resource: "*"
      Tags:
        - Key: Created-in-stack
          Value: !Sub '${AWS::StackId}'
  rDBAccessRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      MaxSessionDuration: !Ref SessionDurationInSec
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: DBAccessRole
      Path: "/"
      Tags:
        - Key: Created-in-stack
          Value: !Sub '${AWS::StackId}'
  rDBAccessNotAllowedRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      MaxSessionDuration: !Ref SessionDurationInSec
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: DBAccessNotAllowedRole
      Path: "/"
      Tags:
        - Key: Created-in-stack
          Value: !Sub '${AWS::StackId}'
  rSQSAccessRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AWSCloudTrailReadOnlyAccess
      MaxSessionDuration: !Ref SessionDurationInSec
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: SQSAccessRole
      Path: "/"
      Tags:
        - Key: Created-in-stack
          Value: !Sub '${AWS::StackId}'
  rSQSAccessNotAllowedRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/AWSCloudTrailReadOnlyAccess
      MaxSessionDuration: !Ref SessionDurationInSec
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: SQSAccessNotAllowedRole
      Path: "/"
      Tags:
        - Key: Created-in-stack
          Value: !Sub '${AWS::StackId}'  
  rAdminRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      MaxSessionDuration: !Ref SessionDurationInSec
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - sts:AssumeRole
            Condition:
              Bool:
                aws:MultiFactorAuthPresent: true
      RoleName: AdminRole
      Path: "/"
      Tags:
        - Key: Created-in-stack
          Value: !Sub '${AWS::StackId}'
  rKMSPOCMsgProcessorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub KMS-POC-MsgProcessor-role-${AWS::Region}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXRayDaemonWriteAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Tags:
        - Key: Created-in-stack
          Value: !Sub '${AWS::StackId}'
  rKMSPOCMsgProcessorLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: KMS-POC-MsgProcessor-policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - dynamodb:*
            Resource:
              - arn:aws:dynamodb:*:*:table/Person
              - arn:aws:dynamodb:*:*:table/Person/*
          -
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      Roles:
        - !Sub KMS-POC-MsgProcessor-role-${AWS::Region}
    DependsOn: rKMSPOCMsgProcessorLambdaRole
